version: "2"
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - godox
    - nlreturn
    - wsl
    - noinlineerr
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    cyclop:
      max-complexity: 20
    dupl:
      threshold: 250
    funlen:
      lines: 150
      statements: 60
    gocognit:
      min-complexity: 20
    interfacebloat:
      max: 10
    lll:
      line-length: 120
    tagalign:
      align: true
      sort: true
      order:
        - json
        - yaml
        - yml
        - toml
        - env
        - env-prefix
        - env-default
        - env-required
        - env-description
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: camel
        use-field-name: true
    varnamelen:
      ignore-names:
        - err
        - ok
        - id
      ignore-decls:
        - wg *sync.WaitGroup
        - wg sync.WaitGroup
    wrapcheck:
      ignore-package-globs:
        - github.com/grinderz/go-libs/*
        - github.com/sethvargo/*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        path: config.go
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
