---
run:
  go: "1.20"
  issues-exit-code: 1
  skip-dirs-use-default: true
  allow-parallel-runners: false

output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  # default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

  # make issues output unique by line, default is true
  # uniq-by-line: true

  # add a prefix to the output file references; default is no prefix
  # path-prefix: ""

  # sorts results by: filepath, line and column
  sort-results: true

linters:
  disable:
    - godox
    - gci
    - exhaustruct
    - gofumpt
    - nlreturn
    - gochecknoinits
    - musttag
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - goconst
    - gocritic
    - godot
    - goerr113
    - gofmt
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacebloat
    - lll
    - loggercheck
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

linters-settings:
  lll:
    line-length: 120
  wrapcheck:
    ignorePackageGlobs:
      - github.com/grinderz/grgo/*
      - github.com/sethvargo/*
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: camel
  interfacebloat:
    # The maximum number of methods allowed for an interface.
    # Default: 10
    max: 10
  varnamelen:
    ignore-names:
      - err
      - ok
      - id
    ignore-decls:
      - wg *sync.WaitGroup
      - wg sync.WaitGroup
  gocognit:
    # Minimal code complexity to report.
    # Default: 30 (but we recommend 10-20)
    min-complexity: 20
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 11
  funlen:
    # Checks the number of lines in a function.
    # If lower than 0, disable the check.
    # Default: 60
    lines: 120
#issues:
#  exclude-rules:
#    - linters:
#        - gosec
#      text: "G402: TLS InsecureSkipVerify may be true"
#    - linters:
#        - goerr113
#      text: "err113: do not define dynamic errors"
