// Code generated by "stringer -type=EngineEnum -linecomment -output engine_enum_string.go"; DO NOT EDIT.

package libmaxprocs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EngineUnknown-0]
	_ = x[EngineDisabled-1]
	_ = x[EngineAuto-2]
	_ = x[EngineDirect-3]
}

const _EngineEnum_name = "unknowndisabledautodirect"

var _EngineEnum_index = [...]uint8{0, 7, 15, 19, 25}

func (i EngineEnum) String() string {
	if i < 0 || i >= EngineEnum(len(_EngineEnum_index)-1) {
		return "EngineEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EngineEnum_name[_EngineEnum_index[i]:_EngineEnum_index[i+1]]
}
